version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: testapp
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - testapp-postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
    volumes:
      - ./:/opt/app
    links:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  testapp-postgres:
